# DISPLAY
min_ratio: .1
min_read: 9

display_summary: True
display_sequence_info: True
display_nucleotide_dist: True

# FUNCTION
destructive_motif_pull: False

# INPUT
motif_consensus_file: 'motif-consensus.fa'
