# if a sequence fulfills either of these minimum requirements, it will be visible
# summary statistics beginning with ** still perform calculations on the hidden sequences
min_ratio: .001
min_read: 9

display_summary: True
display_sequence_info: True
display_nucleotide_dist: True

# fuzzy_motif: true