# FILTER
min_ratio: .1
min_read: 10

# DISPLAY
display_summary: True
display_sequence_info: True
display_nucleotide_dist: True
display_expression: True
display_group_output: True
display_distance_metric: True

# FUNCTION
## one read/isomir matches only one mirna. If multiple matches occur increase motif or set this to TRUE
## if TRUE, quagmir will find mirna with least edit distance and assign read to that motif/mirna
destructive_motif_pull: True
## if seq_end is more than 3 bp longer than consensus_end and contains mismatches 
## discard as possible sequencing error
skip_3p_error: True 
## if seq_end is more than 5 bp longer and consensus seq is minimun 22 bp 
## discard as contaminant
skip_3p_contaminant: True 
## post-transcriptional modification on 5p are biologically unlikely 
## quagmir will check if seq_end contains substitutions compared to consensus_end
skip_5p_substitution: True 

# INPUT
motif_consensus_file: 'motif-consensus.fa'

# OUTPUT
group_output_name: 'cohort1'

# DISTANCE METRIC
deletion_score: 1
insertion_score: 1
substitution_AG: 1 # transition
substitution_GA: 1 # transition
substitution_CT: 1 # transition
substitution_TC: 1 # transition
substitution_AT: 1 # transversion
substitution_TA: 1 # transversion
substitution_AC: 1 # transversion
substitution_CA: 1 # transversion
substitution_GC: 1 # transversion
substitution_CG: 1 # transversion
substitution_GT: 1 # transversion
substitution_TG: 1 # transversion
